/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AAddToTemplateProgramStart extends PProgramStart
{
    private TId _id_;
    private PTypeList _typeList_;

    public AAddToTemplateProgramStart()
    {
        // Constructor
    }

    public AAddToTemplateProgramStart(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PTypeList _typeList_)
    {
        // Constructor
        setId(_id_);

        setTypeList(_typeList_);

    }

    @Override
    public Object clone()
    {
        return new AAddToTemplateProgramStart(
            cloneNode(this._id_),
            cloneNode(this._typeList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddToTemplateProgramStart(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PTypeList getTypeList()
    {
        return this._typeList_;
    }

    public void setTypeList(PTypeList node)
    {
        if(this._typeList_ != null)
        {
            this._typeList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._typeList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._typeList_ == child)
        {
            this._typeList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._typeList_ == oldChild)
        {
            setTypeList((PTypeList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
