/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AAddToRoomPointsRoomType extends PRoomType
{
    private PAstMultiId _astMultiId_;

    public AAddToRoomPointsRoomType()
    {
        // Constructor
    }

    public AAddToRoomPointsRoomType(
        @SuppressWarnings("hiding") PAstMultiId _astMultiId_)
    {
        // Constructor
        setAstMultiId(_astMultiId_);

    }

    @Override
    public Object clone()
    {
        return new AAddToRoomPointsRoomType(
            cloneNode(this._astMultiId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddToRoomPointsRoomType(this);
    }

    public PAstMultiId getAstMultiId()
    {
        return this._astMultiId_;
    }

    public void setAstMultiId(PAstMultiId node)
    {
        if(this._astMultiId_ != null)
        {
            this._astMultiId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astMultiId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astMultiId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astMultiId_ == child)
        {
            this._astMultiId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astMultiId_ == oldChild)
        {
            setAstMultiId((PAstMultiId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
