/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AAddToRoomProgramStart extends PProgramStart
{
    private TId _id_;
    private PRoomType _roomType_;

    public AAddToRoomProgramStart()
    {
        // Constructor
    }

    public AAddToRoomProgramStart(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PRoomType _roomType_)
    {
        // Constructor
        setId(_id_);

        setRoomType(_roomType_);

    }

    @Override
    public Object clone()
    {
        return new AAddToRoomProgramStart(
            cloneNode(this._id_),
            cloneNode(this._roomType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddToRoomProgramStart(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PRoomType getRoomType()
    {
        return this._roomType_;
    }

    public void setRoomType(PRoomType node)
    {
        if(this._roomType_ != null)
        {
            this._roomType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._roomType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._roomType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._roomType_ == child)
        {
            this._roomType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._roomType_ == oldChild)
        {
            setRoomType((PRoomType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
