/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AAstSecondPreciseDir extends PAstSecondPreciseDir
{
    private TFloat _float_;
    private PAstDir _astDir_;

    public AAstSecondPreciseDir()
    {
        // Constructor
    }

    public AAstSecondPreciseDir(
        @SuppressWarnings("hiding") TFloat _float_,
        @SuppressWarnings("hiding") PAstDir _astDir_)
    {
        // Constructor
        setFloat(_float_);

        setAstDir(_astDir_);

    }

    @Override
    public Object clone()
    {
        return new AAstSecondPreciseDir(
            cloneNode(this._float_),
            cloneNode(this._astDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAstSecondPreciseDir(this);
    }

    public TFloat getFloat()
    {
        return this._float_;
    }

    public void setFloat(TFloat node)
    {
        if(this._float_ != null)
        {
            this._float_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._float_ = node;
    }

    public PAstDir getAstDir()
    {
        return this._astDir_;
    }

    public void setAstDir(PAstDir node)
    {
        if(this._astDir_ != null)
        {
            this._astDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._float_)
            + toString(this._astDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._float_ == child)
        {
            this._float_ = null;
            return;
        }

        if(this._astDir_ == child)
        {
            this._astDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._float_ == oldChild)
        {
            setFloat((TFloat) newChild);
            return;
        }

        if(this._astDir_ == oldChild)
        {
            setAstDir((PAstDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
