/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ACopyTProgramStart extends PProgramStart
{
    private PCopyTemplate _copyTemplate_;

    public ACopyTProgramStart()
    {
        // Constructor
    }

    public ACopyTProgramStart(
        @SuppressWarnings("hiding") PCopyTemplate _copyTemplate_)
    {
        // Constructor
        setCopyTemplate(_copyTemplate_);

    }

    @Override
    public Object clone()
    {
        return new ACopyTProgramStart(
            cloneNode(this._copyTemplate_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACopyTProgramStart(this);
    }

    public PCopyTemplate getCopyTemplate()
    {
        return this._copyTemplate_;
    }

    public void setCopyTemplate(PCopyTemplate node)
    {
        if(this._copyTemplate_ != null)
        {
            this._copyTemplate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._copyTemplate_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._copyTemplate_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._copyTemplate_ == child)
        {
            this._copyTemplate_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._copyTemplate_ == oldChild)
        {
            setCopyTemplate((PCopyTemplate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
