/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ACopyPoints extends PCopyPoints
{
    private PAstMultiId _left_;
    private PAstNullableRelation _astNullableRelation_;
    private PAstMultiId _right_;

    public ACopyPoints()
    {
        // Constructor
    }

    public ACopyPoints(
        @SuppressWarnings("hiding") PAstMultiId _left_,
        @SuppressWarnings("hiding") PAstNullableRelation _astNullableRelation_,
        @SuppressWarnings("hiding") PAstMultiId _right_)
    {
        // Constructor
        setLeft(_left_);

        setAstNullableRelation(_astNullableRelation_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ACopyPoints(
            cloneNode(this._left_),
            cloneNode(this._astNullableRelation_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACopyPoints(this);
    }

    public PAstMultiId getLeft()
    {
        return this._left_;
    }

    public void setLeft(PAstMultiId node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public PAstNullableRelation getAstNullableRelation()
    {
        return this._astNullableRelation_;
    }

    public void setAstNullableRelation(PAstNullableRelation node)
    {
        if(this._astNullableRelation_ != null)
        {
            this._astNullableRelation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astNullableRelation_ = node;
    }

    public PAstMultiId getRight()
    {
        return this._right_;
    }

    public void setRight(PAstMultiId node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._astNullableRelation_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._astNullableRelation_ == child)
        {
            this._astNullableRelation_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PAstMultiId) newChild);
            return;
        }

        if(this._astNullableRelation_ == oldChild)
        {
            setAstNullableRelation((PAstNullableRelation) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PAstMultiId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
