/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ACopySProgramStart extends PProgramStart
{
    private PCopyShapes _copyShapes_;

    public ACopySProgramStart()
    {
        // Constructor
    }

    public ACopySProgramStart(
        @SuppressWarnings("hiding") PCopyShapes _copyShapes_)
    {
        // Constructor
        setCopyShapes(_copyShapes_);

    }

    @Override
    public Object clone()
    {
        return new ACopySProgramStart(
            cloneNode(this._copyShapes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACopySProgramStart(this);
    }

    public PCopyShapes getCopyShapes()
    {
        return this._copyShapes_;
    }

    public void setCopyShapes(PCopyShapes node)
    {
        if(this._copyShapes_ != null)
        {
            this._copyShapes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._copyShapes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._copyShapes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._copyShapes_ == child)
        {
            this._copyShapes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._copyShapes_ == oldChild)
        {
            setCopyShapes((PCopyShapes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
