/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ACreatePointProgramStart extends PProgramStart
{
    private PCreatePoint _createPoint_;

    public ACreatePointProgramStart()
    {
        // Constructor
    }

    public ACreatePointProgramStart(
        @SuppressWarnings("hiding") PCreatePoint _createPoint_)
    {
        // Constructor
        setCreatePoint(_createPoint_);

    }

    @Override
    public Object clone()
    {
        return new ACreatePointProgramStart(
            cloneNode(this._createPoint_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACreatePointProgramStart(this);
    }

    public PCreatePoint getCreatePoint()
    {
        return this._createPoint_;
    }

    public void setCreatePoint(PCreatePoint node)
    {
        if(this._createPoint_ != null)
        {
            this._createPoint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._createPoint_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._createPoint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._createPoint_ == child)
        {
            this._createPoint_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._createPoint_ == oldChild)
        {
            setCreatePoint((PCreatePoint) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
