/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ACreateMapProgramStart extends PProgramStart
{
    private PCreateMap _createMap_;

    public ACreateMapProgramStart()
    {
        // Constructor
    }

    public ACreateMapProgramStart(
        @SuppressWarnings("hiding") PCreateMap _createMap_)
    {
        // Constructor
        setCreateMap(_createMap_);

    }

    @Override
    public Object clone()
    {
        return new ACreateMapProgramStart(
            cloneNode(this._createMap_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACreateMapProgramStart(this);
    }

    public PCreateMap getCreateMap()
    {
        return this._createMap_;
    }

    public void setCreateMap(PCreateMap node)
    {
        if(this._createMap_ != null)
        {
            this._createMap_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._createMap_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._createMap_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._createMap_ == child)
        {
            this._createMap_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._createMap_ == oldChild)
        {
            setCreateMap((PCreateMap) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
