/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ACreatePointExtendedCreatePoint extends PCreatePoint
{
    private PAstRelation _astRelation_;
    private TId _id_;

    public ACreatePointExtendedCreatePoint()
    {
        // Constructor
    }

    public ACreatePointExtendedCreatePoint(
        @SuppressWarnings("hiding") PAstRelation _astRelation_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setAstRelation(_astRelation_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new ACreatePointExtendedCreatePoint(
            cloneNode(this._astRelation_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACreatePointExtendedCreatePoint(this);
    }

    public PAstRelation getAstRelation()
    {
        return this._astRelation_;
    }

    public void setAstRelation(PAstRelation node)
    {
        if(this._astRelation_ != null)
        {
            this._astRelation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astRelation_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astRelation_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astRelation_ == child)
        {
            this._astRelation_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astRelation_ == oldChild)
        {
            setAstRelation((PAstRelation) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
