/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ADistanceAstPosition extends PAstPosition
{
    private PAstDis _astDis_;
    private TId _l_;
    private TId _r_;

    public ADistanceAstPosition()
    {
        // Constructor
    }

    public ADistanceAstPosition(
        @SuppressWarnings("hiding") PAstDis _astDis_,
        @SuppressWarnings("hiding") TId _l_,
        @SuppressWarnings("hiding") TId _r_)
    {
        // Constructor
        setAstDis(_astDis_);

        setL(_l_);

        setR(_r_);

    }

    @Override
    public Object clone()
    {
        return new ADistanceAstPosition(
            cloneNode(this._astDis_),
            cloneNode(this._l_),
            cloneNode(this._r_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADistanceAstPosition(this);
    }

    public PAstDis getAstDis()
    {
        return this._astDis_;
    }

    public void setAstDis(PAstDis node)
    {
        if(this._astDis_ != null)
        {
            this._astDis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astDis_ = node;
    }

    public TId getL()
    {
        return this._l_;
    }

    public void setL(TId node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TId getR()
    {
        return this._r_;
    }

    public void setR(TId node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astDis_)
            + toString(this._l_)
            + toString(this._r_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astDis_ == child)
        {
            this._astDis_ = null;
            return;
        }

        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astDis_ == oldChild)
        {
            setAstDis((PAstDis) newChild);
            return;
        }

        if(this._l_ == oldChild)
        {
            setL((TId) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
