/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ADownDirAstDir extends PAstDir
{
    private TDown _down_;

    public ADownDirAstDir()
    {
        // Constructor
    }

    public ADownDirAstDir(
        @SuppressWarnings("hiding") TDown _down_)
    {
        // Constructor
        setDown(_down_);

    }

    @Override
    public Object clone()
    {
        return new ADownDirAstDir(
            cloneNode(this._down_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADownDirAstDir(this);
    }

    public TDown getDown()
    {
        return this._down_;
    }

    public void setDown(TDown node)
    {
        if(this._down_ != null)
        {
            this._down_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._down_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._down_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._down_ == child)
        {
            this._down_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._down_ == oldChild)
        {
            setDown((TDown) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
