/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AERelationAstNullableRelation extends PAstNullableRelation
{
    private PAstPreciseDir _astPreciseDir_;

    public AERelationAstNullableRelation()
    {
        // Constructor
    }

    public AERelationAstNullableRelation(
        @SuppressWarnings("hiding") PAstPreciseDir _astPreciseDir_)
    {
        // Constructor
        setAstPreciseDir(_astPreciseDir_);

    }

    @Override
    public Object clone()
    {
        return new AERelationAstNullableRelation(
            cloneNode(this._astPreciseDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAERelationAstNullableRelation(this);
    }

    public PAstPreciseDir getAstPreciseDir()
    {
        return this._astPreciseDir_;
    }

    public void setAstPreciseDir(PAstPreciseDir node)
    {
        if(this._astPreciseDir_ != null)
        {
            this._astPreciseDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astPreciseDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astPreciseDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astPreciseDir_ == child)
        {
            this._astPreciseDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astPreciseDir_ == oldChild)
        {
            setAstPreciseDir((PAstPreciseDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
