/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AProgramStart extends PProgramStart
{

    public AProgramStart()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AProgramStart();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramStart(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
