/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class ARelationCoordinateAstRelation extends PAstRelation
{
    private PAstCoordinate _astCoordinate_;

    public ARelationCoordinateAstRelation()
    {
        // Constructor
    }

    public ARelationCoordinateAstRelation(
        @SuppressWarnings("hiding") PAstCoordinate _astCoordinate_)
    {
        // Constructor
        setAstCoordinate(_astCoordinate_);

    }

    @Override
    public Object clone()
    {
        return new ARelationCoordinateAstRelation(
            cloneNode(this._astCoordinate_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelationCoordinateAstRelation(this);
    }

    public PAstCoordinate getAstCoordinate()
    {
        return this._astCoordinate_;
    }

    public void setAstCoordinate(PAstCoordinate node)
    {
        if(this._astCoordinate_ != null)
        {
            this._astCoordinate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._astCoordinate_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._astCoordinate_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._astCoordinate_ == child)
        {
            this._astCoordinate_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._astCoordinate_ == oldChild)
        {
            setAstCoordinate((PAstCoordinate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
