/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AStartAstDis extends PAstDis
{
    private TStart _start_;

    public AStartAstDis()
    {
        // Constructor
    }

    public AStartAstDis(
        @SuppressWarnings("hiding") TStart _start_)
    {
        // Constructor
        setStart(_start_);

    }

    @Override
    public Object clone()
    {
        return new AStartAstDis(
            cloneNode(this._start_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStartAstDis(this);
    }

    public TStart getStart()
    {
        return this._start_;
    }

    public void setStart(TStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._start_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._start_ == oldChild)
        {
            setStart((TStart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
