/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class AUpDirAstDir extends PAstDir
{
    private TUp _up_;

    public AUpDirAstDir()
    {
        // Constructor
    }

    public AUpDirAstDir(
        @SuppressWarnings("hiding") TUp _up_)
    {
        // Constructor
        setUp(_up_);

    }

    @Override
    public Object clone()
    {
        return new AUpDirAstDir(
            cloneNode(this._up_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUpDirAstDir(this);
    }

    public TUp getUp()
    {
        return this._up_;
    }

    public void setUp(TUp node)
    {
        if(this._up_ != null)
        {
            this._up_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._up_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._up_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._up_ == child)
        {
            this._up_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._up_ == oldChild)
        {
            setUp((TUp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
