/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TCoordinates extends Token
{
    public TCoordinates()
    {
        super.setText("coordinates");
    }

    public TCoordinates(int line, int pos)
    {
        super.setText("coordinates");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCoordinates(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCoordinates(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCoordinates text.");
    }
}
