/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TDown extends Token
{
    public TDown()
    {
        super.setText("down");
    }

    public TDown(int line, int pos)
    {
        super.setText("down");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDown(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDown(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDown text.");
    }
}
