/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TFloor extends Token
{
    public TFloor()
    {
        super.setText("floor");
    }

    public TFloor(int line, int pos)
    {
        super.setText("floor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFloor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFloor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFloor text.");
    }
}
