/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TLeft extends Token
{
    public TLeft()
    {
        super.setText("left");
    }

    public TLeft(int line, int pos)
    {
        super.setText("left");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLeft(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeft(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLeft text.");
    }
}
