/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TNearstart extends Token
{
    public TNearstart()
    {
        super.setText("nearstart");
    }

    public TNearstart(int line, int pos)
    {
        super.setText("nearstart");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNearstart(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNearstart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNearstart text.");
    }
}
