/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TRectangle extends Token
{
    public TRectangle()
    {
        super.setText("rectangle");
    }

    public TRectangle(int line, int pos)
    {
        super.setText("rectangle");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRectangle(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRectangle(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRectangle text.");
    }
}
