/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TRoom extends Token
{
    public TRoom()
    {
        super.setText("room");
    }

    public TRoom(int line, int pos)
    {
        super.setText("room");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRoom(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRoom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRoom text.");
    }
}
