/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TShapes extends Token
{
    public TShapes()
    {
        super.setText("shapes");
    }

    public TShapes(int line, int pos)
    {
        super.setText("shapes");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TShapes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShapes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TShapes text.");
    }
}
