/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TTemplate extends Token
{
    public TTemplate()
    {
        super.setText("template");
    }

    public TTemplate(int line, int pos)
    {
        super.setText("template");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTemplate(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTemplate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTemplate text.");
    }
}
