/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.node;

import MapLang.analysis.*;

@SuppressWarnings("nls")
public final class TUp extends Token
{
    public TUp()
    {
        super.setText("up");
    }

    public TUp(int line, int pos)
    {
        super.setText("up");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUp(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUp(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUp text.");
    }
}
