/* This file was generated by SableCC (http://www.sablecc.org/). */

package MapLang.parser;

import MapLang.node.*;
import MapLang.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTStar(@SuppressWarnings("unused") TStar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 1;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 3;
    }

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 4;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 5;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 6;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 7;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 8;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 9;
    }

    @Override
    public void caseTCreate(@SuppressWarnings("unused") TCreate node)
    {
        this.index = 10;
    }

    @Override
    public void caseTMap(@SuppressWarnings("unused") TMap node)
    {
        this.index = 11;
    }

    @Override
    public void caseTPoint(@SuppressWarnings("unused") TPoint node)
    {
        this.index = 12;
    }

    @Override
    public void caseTFrom(@SuppressWarnings("unused") TFrom node)
    {
        this.index = 13;
    }

    @Override
    public void caseTTo(@SuppressWarnings("unused") TTo node)
    {
        this.index = 14;
    }

    @Override
    public void caseTAt(@SuppressWarnings("unused") TAt node)
    {
        this.index = 15;
    }

    @Override
    public void caseTBy(@SuppressWarnings("unused") TBy node)
    {
        this.index = 16;
    }

    @Override
    public void caseTRight(@SuppressWarnings("unused") TRight node)
    {
        this.index = 17;
    }

    @Override
    public void caseTLeft(@SuppressWarnings("unused") TLeft node)
    {
        this.index = 18;
    }

    @Override
    public void caseTUp(@SuppressWarnings("unused") TUp node)
    {
        this.index = 19;
    }

    @Override
    public void caseTDown(@SuppressWarnings("unused") TDown node)
    {
        this.index = 20;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 21;
    }

    @Override
    public void caseTFloat(@SuppressWarnings("unused") TFloat node)
    {
        this.index = 22;
    }

    @Override
    public void caseTCopy(@SuppressWarnings("unused") TCopy node)
    {
        this.index = 23;
    }

    @Override
    public void caseTAdd(@SuppressWarnings("unused") TAdd node)
    {
        this.index = 24;
    }

    @Override
    public void caseTRoom(@SuppressWarnings("unused") TRoom node)
    {
        this.index = 25;
    }

    @Override
    public void caseTTemplate(@SuppressWarnings("unused") TTemplate node)
    {
        this.index = 26;
    }

    @Override
    public void caseTTemplates(@SuppressWarnings("unused") TTemplates node)
    {
        this.index = 27;
    }

    @Override
    public void caseTShape(@SuppressWarnings("unused") TShape node)
    {
        this.index = 28;
    }

    @Override
    public void caseTLine(@SuppressWarnings("unused") TLine node)
    {
        this.index = 29;
    }

    @Override
    public void caseTCoordinates(@SuppressWarnings("unused") TCoordinates node)
    {
        this.index = 30;
    }

    @Override
    public void caseTIn(@SuppressWarnings("unused") TIn node)
    {
        this.index = 31;
    }

    @Override
    public void caseTFloor(@SuppressWarnings("unused") TFloor node)
    {
        this.index = 32;
    }

    @Override
    public void caseTRectangle(@SuppressWarnings("unused") TRectangle node)
    {
        this.index = 33;
    }

    @Override
    public void caseTCircle(@SuppressWarnings("unused") TCircle node)
    {
        this.index = 34;
    }

    @Override
    public void caseTPoints(@SuppressWarnings("unused") TPoints node)
    {
        this.index = 35;
    }

    @Override
    public void caseTShapes(@SuppressWarnings("unused") TShapes node)
    {
        this.index = 36;
    }

    @Override
    public void caseTDoorway(@SuppressWarnings("unused") TDoorway node)
    {
        this.index = 37;
    }

    @Override
    public void caseTWindow(@SuppressWarnings("unused") TWindow node)
    {
        this.index = 38;
    }

    @Override
    public void caseTExit(@SuppressWarnings("unused") TExit node)
    {
        this.index = 39;
    }

    @Override
    public void caseTStart(@SuppressWarnings("unused") TStart node)
    {
        this.index = 40;
    }

    @Override
    public void caseTNearstart(@SuppressWarnings("unused") TNearstart node)
    {
        this.index = 41;
    }

    @Override
    public void caseTHalfway(@SuppressWarnings("unused") THalfway node)
    {
        this.index = 42;
    }

    @Override
    public void caseTNearend(@SuppressWarnings("unused") TNearend node)
    {
        this.index = 43;
    }

    @Override
    public void caseTEnd(@SuppressWarnings("unused") TEnd node)
    {
        this.index = 44;
    }

    @Override
    public void caseTMove(@SuppressWarnings("unused") TMove node)
    {
        this.index = 45;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 46;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 47;
    }
}
